spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
